services:
  web:
    command: bin/web
    domain: ${HOST}
    environment:
      - AUTHENTICATION=
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - GITHUB_ENTERPRISE_CLIENT_ID=
      - GITHUB_ENTERPRISE_CLIENT_SECRET=
      - GITHUB_ENTERPRISE_HOST=
      - GITHUB_WEBHOOK_SECRET=
      - GITLAB_CLIENT_ID=
      - GITLAB_CLIENT_SECRET=
      - HOST
      - LDAP_ADDR=
      - LDAP_BIND=
      - LICENSE_KEY
      - RACK_KEY
      - SESSION_KEY
      - SLACK_CLIENT_ID=
      - SLACK_CLIENT_SECRET=
      - TABLE_PREFIX
      - WORKER_QUEUE
    health:
      interval: 30
      path: /check
    image: enterprise.convox.com/console:2.0.1
    init: true
    port: https:3000
    scale:
      count: 2
      cpu: 64
      memory: 500
    test: make test
  worker:
    command: bin/worker
    environment:
      - AWS_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - GITHUB_ENTERPRISE_HOST=
      - HOST
      - LICENSE_KEY
      - RACK_KEY
      - TABLE_PREFIX
      - TUNNEL_HOST=
      - WORKER_QUEUE
    image: enterprise.convox.com/console:2.0.1
    init: true
    scale:
      count: 1
      cpu: 128
      memory: 500
timers:
  rack-webhooks:
    command: task rack-webhooks
    schedule: "*/5 * * * ? *"
    service: worker
