audit-logs:
  key: id
  ttl: ttl
  indexes:
    organization-id: organization,timestamp
    rack: rack,timestamp
challenges:
  key: id
  ttl: ttl
deploy-keys:
  key: id
  indexes:
    key-hash: key-hash
    organization-id: organization-id
installs:
  key: id
  indexes:
    organization-id: organization-id
integrations:
  key: id
  indexes:
    organization-id: organization-id
jobs:
  key: id
  indexes:
    created: created
    job-created-org: organization-id,created
    organization-id: organization-id
    status-created: status,created
    workflow-id-created: workflow-id,created
organization-invites:
  key: id
  indexes:
    email: email
    organization-id: organization-id
    token: token
organizations:
  key: id
  indexes:
    name: name
racks:
  key: id
  indexes:
    organization-id: organization-id
sessions:
  key: id
  ttl: ttl
  indexes:
    user-id: user-id
tokens:
  key: id
  indexes:
    user-id: user-id
users:
  key: id
  indexes:
    api-key-hash: api-key-hash
    email: email
    github-id: github-id
    password-reset-token: password-reset-token
webhooks:
  key: id
  indexes:
    app-id: app-id
    integration-id: integration-id
    rack-id: rack-id
workflows:
  key: id
  indexes:
    integration-id: integration-id
    name: name
    organization-id: organization-id
    trigger-id: trigger-id
